apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend
 labels:
   app: backend
spec:
 replicas: 1
 selector:
   matchLabels:
     app: backend
 template:
   metadata:
     labels:
       app: backend
   spec:
     containers:
     - name: node-backend
       image: nicolass03/dsfinal-back
       ports:
       - containerPort: 32000
       env:
        - name: DATABASE_URL
          value: db-service

---

apiVersion: v1
kind: Service
metadata:
 name: back-service
 labels:
   app: backend
spec:
 type: ClusterIP
 selector:
   app: backend
 ports:
 - port: 32000
   targetPort: 8089