apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
   app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
         app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
     containers:
     - name: frontend
       image: nicolass03/dsfinal-front:latest
       ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080