apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
   app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
         app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
     containers:
     - name: backend
       image: symghoul/midterm3back:0.1.0
       ports:
        - containerPort: 8089

---

apiVersion: v1
kind: Service
metadata:
 name: backsvc
 labels:
  app: backsvc
spec:
 selector:
  app: backsvc
 ports:
  - protocol: TCP
    port: 8089
    targetPort: 8089
    name: http
